name: gh-pages publish

on:
  push:
    branches: 
      - master
      - dev
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Build Doc with Sphinx
      run: |
        pip install .
        pip install -U sphinx sphinx-rtd-theme
        sphinx-build -b html ./docs/source ./docs/build
    - name: Deploy Dev Doc
      if: ${{github.ref == 'refs/heads/dev'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./docs/build
        destination_dir: dev
    - name: Deploy Stable Doc
      if: ${{github.ref == 'refs/heads/master'}}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{secrets.GITHUB_TOKEN}}
        publish_dir: ./docs/build
        destination_dir: stable
